<?php
/**
 * @var \Codilar\Vendor\Block\View $block
 */
$vendors = $block->getVendor();
?>
<div class="vendor-listing">
    <h1>Vendor List</h1>
    <?php if (count($vendors) > 0): ?>
        <table>
            <tr>
                <th><?php echo __('Id') ?></th>
                <th><?php echo __('Vendor Name') ?></th>
                <th><?php echo __('Vendor Website')?></th>
                <th><?php echo __('Vendor email')?></th>
                <th><?php echo __('Vendor description')?></th>
            </tr>
            <?php foreach ($block->getVendor() as $vendor): ?>
                <tr>
                    <td><?php echo $vendor->getEntityId()?></td>
                    <td><a href="<?php echo $block->getVendorUrl(). 'entity_id/' . $vendor->getEntityId() ?>"><?php echo $vendor->getVendorName()?></a></td>
                    <td><?php echo $vendor->getWebsite()?></td>
                    <td><?php echo $vendor->getEmail()?></td>
                    <td><?php echo $vendor->getDescription()?></td>
                </tr>
            <?php endforeach; ?>
            </thead>
        </table>
    <?php else: ?>
        <h3>Vendor List is Empty</h3>
    <?php endif; ?>
</div>
